version: '3.8'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mysql:
    image: 'mysql:8.0'
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: {your_password}
      MYSQL_DATABASE: {your_database}
      MYSQL_USER: {your_optional_user}
      MYSQL_PASSWORD: {your_optional_user_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data: